module.exports = {
    testTimeout: 30000,
    preset: 'ts-jest',
    testEnvironment: 'node',
    moduleFileExtensions: ['js', 'json', 'ts'],
    roots: ['<rootDir>/src/'],
    testRegex: '.*\\.test\\.ts$',
    workerIdleMemoryLimit: '1k',
    transform: {
        '^.+\\.(t|j)s$': ['ts-jest', { isolatedModules: true }],
    },
    moduleNameMapper: {
        '^@/decorators$': '<rootDir>/src/decorators',
        '^@/entities/(.*)$': '<rootDir>/src/entities/$1',
        '^@/utils/(.*)$': '<rootDir>/src/utils/$1',
        '^@/central/(.*)$': '<rootDir>/src/central-service/$1',
        '^@/auth/(.*)$': '<rootDir>/src/auth-service/$1',
        '^@/guards/(.*)$': '<rootDir>/src/guards/$1',
        '^@/reports/(.*)$': '<rootDir>/src/reports-service/$1',
        '^@/connector/(.*)$': '<rootDir>/src/connector-service/$1',
        '^@/act/(.*)$': '<rootDir>/src/act-service/$1',
        '^@/calculations/(.*)$': '<rootDir>/src/calculations-service/$1',
        '^@/log/(.*)$': '<rootDir>/src/log-service/$1',
        '^@/shared/(.*)$': '<rootDir>/src/shared/$1',
    },
    collectCoverageFrom: ['**/*.(t|j)s'],
    coverageDirectory: './coverage',
    coverageReporters: ['text', 'cobertura'],
}
